### ISSUE TITLE
Issue adding tslint in react-slingshot

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [typescriptcrew/ts-react-slingshot#23] opened 2017-02-18 18:08 UTC
Sorry duplicate issue.

When I add the tslint key to the webpack.config.dev.js like you have I get an error.
tslint: {
configFile: './tslint.json',
emitErrors: true,
failOnHint: true
},

However, I can add it to the module section like so without any issues:
{test: /.ts$/, enforce: 'pre', exclude: /node_modules/, loader: 'tslint-loader', options: {emitErrors: true, failOnHint: true, tsConfigFile: 'tsconfig.json'}},

Does that make sense? Also, my unit tests are in different folders under components in the src folder. However the tests did n't run and had to move to a folder tests I guess because of this line in the package.json:
"testRegex": "/tests/.*\.(ts|tsx|js)$"

How can I change it so it looks at the folders and subfolders under components?

Thirdly, I just need to add the tslint configuration to the webpack.config.dev.js, right and not the webpack.config.prod.js, right?

Thanks.

**Comment by nickytonline** [comment] 2017-09-24 21:33
I'm going to take a look at this this evening. Been pretty busy with life 😉.

**Comment by nickytonline** [comment] 2017-09-26 02:00
Closing as it's a duplicate of #22.

**Closed by nickytonline** 2017-09-26 02:00 UTC
